[build]
  # This command builds your site.
  command = "npm run build"
  # This is the directory that contains the built site.
  publish = "dist"

[context.production.environment]
  # Set environment variables for the production build.
  # Vite requires env vars to be prefixed with VITE_.
  VITE_API_URL = "/api"
  NODE_VERSION = "18"

# This redirect rule is for your single-page application (SPA).
# It ensures that any direct navigation to a route like /about or /contact
# is handled by your index.html file. It must be the last redirect.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This is the proxy redirect for your API calls.
# It forwards any request from /api/... to your backend server.
# This rule must come BEFORE the SPA redirect rule.
[[redirects]]
  from = "/api/*"
  to = "https://avotak-backend.onrender.com/api/:splat"
  status = 200
  force = true
