[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://avotak-backend.onrender.com/api/:splat"
  status = 200
  force = true
  # headers = {Access-Control-Allow-Origin = "*"}  <-- Let's comment this out or remove it

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "/api"