[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://avotak-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
